### ISSUE TITLE
module load error 

### ISSUE THREAD

**Issue by Cricen** [wwce/terraform#8]
Hello, 

I'm a bit new to terraform but i'm getting the following error when trying to init.  

`Error: Error loading modules: module ngfw1: Error parsing .terraform/modules/7d1791043736baffafabfc9b3b038300/main.tf: At 51:18: nested object expected: LBRACE got: ASSIGN`

The 'include' on line 51 in vm-sereis/main.tf

**Comment by djspears** [comment]
Fixed
